### PR TITLE
J is learning fork

### PR DESCRIPTION
**Pull request by yanaf02**
Code is added, please take a look and merge into the master at your earliest convenience. 

Thanks!

### CODE REVIEW

**Comment by CybertekSchool** [comment]
looks cool J

**Comment by slokostic3212** [comment]
great job

**Comment by olcaycanitez** [comment]
keep going

**Comment by RGallardo** [comment]
Nicely done Yana

**Comment by milenasbkn** [comment]
Looks great

**Comment by yanaf02** [comment]
Thank you!

**Comment by tenus88** [comment]
hello hello

**Comment by CybertekSchool** [comment]
ok you might wanna add your full name so we can merge

**Comment by abzion7** [comment]
nice job

**Comment by MickoCar** [comment]
I think you should still work on it. :)

**Comment by ygayypov** [comment]
Perfectooo

**Comment by cmert2017** [comment]
it looks it works

**Comment by Igruss** [comment]
HELLO

**Comment by yanaf02** [comment]
Im here

**Comment by abzalaltayev** [comment]
mom im  on youtube

**Comment by ViolettaMal** [comment]
Hey!))

**Comment by Hagaliyev** [comment]
What an awesome Code! OMG

**Comment by anam88** [comment]
looks cool

**Comment by AnelZhaksybergenova** [comment]
great

**Comment by rumeysakdogan** [comment]
Good job!

**Comment by ZulfiyyaM** [comment]
cool code))))

**Comment by slokostic3212** [comment]
again great job - but who are you?

**Comment by elmirakamil** [comment]
J is lost

**Comment by orazovalibek** [comment]
please comment who is J

**Comment by Shekur2020** [comment]
Looks JJJ-cool

**Comment by dreaguti** [comment]
Nice!

**Comment by jmvalmeria** [comment]
Nice job

**Comment by IssB20** [comment]
ok I will merge

**Comment by AliParmar** [comment]
Have a nice day J!

**Comment by hasankayman** [comment]
Good job!!

**Comment by LuisaFRojas** [comment]
Good job J!!

**Comment by ziiadin** [comment]
So funny Akbars magic)

**Comment by todoriva1** [comment]
spojio ga

**Comment by musamoylam** [comment]
Nice to see you guys;)

**Comment by sbabayev** [comment]
good job J :D

**Review by lyopa77 — COMMENTED** [review]
vv

**Pull request merged**
