### PR TITLE
bulentGunerli is learning Fork

### PR DESCRIPTION
**Pull request by bugunerli**
Codes are added, please take a look at it

### CODE REVIEW

**Comment by ziiadin** [comment]
Man i like it)) )

**Comment by bugunerli** [comment]
Did you check my codes ?

**Comment by journeyAa** [comment]
nice job Bulent

**Comment by tenus88** [comment]
hey-hey

**Comment by RGallardo** [comment]
Looks awesome! well done

**Comment by AishaAydin** [comment]
cool!!

**Comment by IssB20** [comment]
check your email plz

**Comment by AliParmar** [comment]
Bulent! You are the lucky winner!

**Comment by orazovalibek** [comment]
Great job !!!

**Comment by urumqi-bagang** [comment]
Hi bulent

**Comment by ElkemEmet** [comment]
looks good, u are super man

**Comment by CybertekSchool** [comment]
look cool , you have made your first open source contribution , keep up the good work

**Comment by musamoylam** [comment]
Good job budd

**Comment by ygayypov** [comment]
Good in learning

**Comment by Gahbella** [comment]
looks cool , your first open source contribution

**Comment by suguz06** [comment]
good job!!

**Comment by seckinceylan** [comment]
> please merge my codes in master

nice job

**Comment by abdennouressaihi** [comment]
test test test

**Comment by sbabayev** [comment]
Awesome!

**Comment by iskrenovas** [comment]
Hi

**Comment by elomariahmed** [comment]
good job

**Comment by MakhmudAkhmedov** [comment]
Looks Cool

**Comment by Nurbiye** [comment]
great~~

**Comment by Alex-B-I** [comment]
Cool

**Comment by LuisaFRojas** [comment]
Great Job Bulent!!!!

**Comment by jmvalmeria** [comment]
Good job!!!

**Comment by EdwardRojas** [comment]
Winner, winner!

**Comment by Hagaliyev** [comment]
Well done, Bulent!

**Comment by todoriva1** [comment]
dobro je

**Comment by AliNijat** [comment]
Great!

**Comment by sayeemraza** [comment]
great work

**Pull request merged**
